version: '3.4'

services:
  
  mssql-server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1430:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - webproxy


  livraria.net.api:
    image: ${DOCKER_REGISTRY-}livrarianetapi
    build:
      context: .
      dockerfile: src/livraria.net.api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Api-StringBd:Server=mssql-server, 1433;Initial Catalog=livrarianet;User ID=SA;Password=root"
    ports:
      - "5101:80"
    depends_on:
      - mssql-server
    networks:
      - webproxy

  mongoDb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
    networks:
       - webproxy

  # Link de acesso ao RabbitMQ pelo navegador http://localhost:15672
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - webproxy

networks:
  webproxy:
    driver: bridge

volumes:
  mssql_data:
  rabbitmq_data:
  rabbitmq_log:
  mongo_data:
