version: '3.4'

services:
  
  mssql-server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1430:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - webproxy


  livraria.net.api:
    image: ${DOCKER_REGISTRY-}livrarianetapi
    build:
      context: .
      dockerfile: src/livraria.net.api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Api-StringBd:Server=mssql-server, 1433;Initial Catalog=livrarianet;User ID=SA;Password=root"
    ports:
      - "5101:80"
    depends_on:
      - mssql-server
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge

volumes:
  mssql_data:
